version: "3"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: development
    ports:
      - "3306:3306"

  web:
    image: nginx:latest
    ports:
      - "9000:80"

  maildev:
    image: maildev/maildev
    ports:
      - "1025:1025"
      - "1080:1080"
