name: Test Go

on:
  push:
    branches: [ "**" ]

jobs:
  Unit_Tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: docker.io/library/mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: testing
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 3306:3306
      smtp:
        image: docker.io/maildev/maildev:latest
        options: --health-cmd "echo 'skip'" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 1025:1025
      webapp:
        image: docker.io/library/nginx:latest
        options: --health-cmd "echo 'skip'" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 9000:9000
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.4

    - name: Tests
      uses: ncruces/go-coverage-report@main
      env:
        MYSQL_USER: root
        MYSQL_PASS: testing
        SMTP_PORT: 1025
        LOG_LEVEL: 1
        JWT_SECRET: testjwtsecret

  Code_Quality:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.4

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...

  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.4

    - name: Build
      run: go build -v -a .
      env:
        CGO_ENABLED: 0

  Docker_Package:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.4

    - name: Build
      run: go build -v -a .
      env:
        CGO_ENABLED: 0

    - name: Build an image from Dockerfile
      run: |
        docker build -t docker.io/papeben/gatehouse:${{ github.sha }} .
        docker run -d --name testcontainer docker.io/papeben/gatehouse:${{ github.sha }}
        sleep 5
        docker exec testcontainer echo "Online"
        docker stop testcontainer

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/papeben/gatehouse:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'


